services:
  - type: web
    name: whatsapp-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py whatsapp-agent-python:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 5000
      - key: LOG_LEVEL
        value: INFO
      - key: HEALTH_LOG_LEVEL
        value: DEBUG
    healthCheckPath: /health 