name: Reminder Evaluation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'agents/reminder_agent/**'
      - 'test_data/reminder_test_cases.json'
      - 'scripts/evaluate_reminder.py'
      - 'scripts/generate_html_report.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'agents/reminder_agent/**'
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directories
      run: mkdir -p test_data test_results docs
      
    - name: Create test cases file if it doesn't exist
      run: |
        if [ ! -f test_data/reminder_test_cases.json ]; then
          echo '[]' > test_data/reminder_test_cases.json
        fi
    
    - name: Run reminder evaluations
      run: python scripts/evaluate_reminder.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    
    - name: Generate HTML report
      run: python scripts/generate_html_report.py
    
    - name: Upload evaluation results
      uses: actions/upload-artifact@v2
      with:
        name: reminder-evaluation-results
        path: test_results/
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs